/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.PostController;

/**
 *
 * @author Salim El Moussaoui <salim.elmoussaoui.afpa2017@gmail.com>
 */
public class PostListView extends javax.swing.JPanel {
    private PostController postController;
    /**
     * Creates new form PostListView
     */
    public PostListView(PostController postController) {
        initComponents();
        
        this.postController = postController;
        PostItemView postItemView = new PostItemView();
        this.postController.listPost(this, postItemView);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jp_bodyListPost = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        jLabel1.setText("Liste des article");
        add(jLabel1, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout jp_bodyListPostLayout = new javax.swing.GroupLayout(jp_bodyListPost);
        jp_bodyListPost.setLayout(jp_bodyListPostLayout);
        jp_bodyListPostLayout.setHorizontalGroup(
            jp_bodyListPostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jp_bodyListPostLayout.setVerticalGroup(
            jp_bodyListPostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 284, Short.MAX_VALUE)
        );

        add(jp_bodyListPost, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jp_bodyListPost;
    // End of variables declaration//GEN-END:variables
}
