/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.PostController;
import javax.swing.JScrollPane;

/**
 *
 * @author Salim El Moussaoui <salim.elmoussaoui.afpa2017@gmail.com>
 */
public class PostListView extends javax.swing.JPanel {
    private PostController postController;
    /**
     * Creates new form PostListView
     */
    public PostListView(PostController postController) {
        initComponents();
        System.out.println("test");
        this.postController = postController;
      
       this.jp_bodyListPost = this.postController.listPost(this.jp_bodyListPost);       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jp_bodyListPost = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        jLabel1.setText("Liste des article");
        add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jScrollPane1.setMinimumSize(new java.awt.Dimension(1020, 600));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(1000, 600));

        jp_bodyListPost.setBackground(new java.awt.Color(255, 255, 255));
        jp_bodyListPost.setLayout(new java.awt.GridBagLayout());
        jScrollPane1.setViewportView(jp_bodyListPost);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jp_bodyListPost;
    // End of variables declaration//GEN-END:variables
}
